"""Document Store -- DynamoDB-backed DOCUMENT# entity CRUD with version tracking.

Phase 3 Step 15. Stores acquisition documents (SOW, IGCE, etc.) generated by
EAGLE agents. Supports versioning with automatic supersession of prior versions.

Entity format:
    PK:  DOCUMENT#{tenant_id}
    SK:  DOCUMENT#{package_id}#{doc_type}#{version}

GSI (GSI1):
    GSI1PK:  TENANT#{tenant_id}
    GSI1SK:  DOCUMENT#{package_id}#{doc_type}#{version:04d}
"""
import os
import uuid
import logging
from datetime import datetime
from typing import Optional

import boto3
from botocore.exceptions import BotoCoreError, ClientError
from boto3.dynamodb.conditions import Key

logger = logging.getLogger('eagle.document_store')

# -- Configuration --------------------------------------------------------
TABLE_NAME = os.getenv('EAGLE_SESSIONS_TABLE', 'eagle')
AWS_REGION = os.getenv('AWS_REGION', 'us-east-1')

# -- DynamoDB Client (lazy singleton) -------------------------------------
_dynamodb = None


def _get_dynamodb():
    global _dynamodb
    if _dynamodb is None:
        _dynamodb = boto3.resource('dynamodb', region_name=AWS_REGION)
    return _dynamodb


def _get_table():
    return _get_dynamodb().Table(TABLE_NAME)


# -- Helpers ---------------------------------------------------------------

def _item_to_dict(item) -> dict:
    """Convert a raw DynamoDB item to a plain dict."""
    return dict(item)


def _sk(package_id: str, doc_type: str, version: int) -> str:
    return f'DOCUMENT#{package_id}#{doc_type}#{version}'


def _gsi1_sk(package_id: str, doc_type: str, version: int) -> str:
    return f'DOCUMENT#{package_id}#{doc_type}#{version:04d}'


# -- Core CRUD -------------------------------------------------------------

def create_document(
    tenant_id: str,
    package_id: str,
    doc_type: str,
    content: str,
    generated_by: str,
    session_id: Optional[str] = None,
    template_id: Optional[str] = None,
) -> dict:
    """Create a new versioned document, superseding all previous versions.

    Scans existing docs for this package + doc_type, takes the highest version
    found, writes new doc at version N+1 (or v1 if none exist), then marks all
    prior versions as superseded.

    Returns the newly created document dict.
    """
    table = _get_table()
    now = datetime.utcnow().isoformat()

    existing = get_document_history(tenant_id, package_id, doc_type)
    next_version = (max(d['version'] for d in existing) + 1) if existing else 1

    document_id = str(uuid.uuid4())

    item: dict = {
        'PK': f'DOCUMENT#{tenant_id}',
        'SK': _sk(package_id, doc_type, next_version),
        'GSI1PK': f'TENANT#{tenant_id}',
        'GSI1SK': _gsi1_sk(package_id, doc_type, next_version),
        'document_id': document_id,
        'package_id': package_id,
        'doc_type': doc_type,
        'content': content,
        'version': next_version,
        'status': 'draft',
        'generated_by': generated_by,
        'created_at': now,
    }
    if session_id is not None:
        item['session_id'] = session_id
    if template_id is not None:
        item['template_id'] = template_id

    try:
        table.put_item(Item=item)
        logger.debug(
            'document_store.create_document: [%s/%s/%s] v%s created',
            tenant_id, package_id, doc_type, next_version,
        )
    except (ClientError, BotoCoreError) as e:
        logger.error('document_store.create_document failed: %s', e)
        raise

    for prior in existing:
        if prior['status'] != 'superseded':
            try:
                table.update_item(
                    Key={
                        'PK': f'DOCUMENT#{tenant_id}',
                        'SK': _sk(package_id, doc_type, prior['version']),
                    },
                    UpdateExpression='SET #s = :superseded',
                    ExpressionAttributeNames={'#s': 'status'},
                    ExpressionAttributeValues={':superseded': 'superseded'},
                )
            except (ClientError, BotoCoreError) as e:
                logger.warning(
                    'document_store.create_document: failed to supersede v%s: %s',
                    prior['version'], e,
                )

    return item


def get_document(
    tenant_id: str,
    package_id: str,
    doc_type: str,
    version: Optional[int] = None,
) -> Optional[dict]:
    """Fetch a document by tenant, package, doc_type, and optional version.

    If version is None, returns the latest (highest version number).
    Returns None if not found.
    """
    if version is not None:
        try:
            table = _get_table()
            response = table.get_item(
                Key={
                    'PK': f'DOCUMENT#{tenant_id}',
                    'SK': _sk(package_id, doc_type, version),
                }
            )
            raw = response.get('Item')
            return _item_to_dict(raw) if raw else None
        except (ClientError, BotoCoreError) as e:
            logger.error('document_store.get_document failed: %s', e)
            return None

    history = get_document_history(tenant_id, package_id, doc_type)
    if not history:
        return None
    return max(history, key=lambda d: d['version'])


def finalize_document(
    tenant_id: str,
    package_id: str,
    doc_type: str,
    version: int,
) -> Optional[dict]:
    """Transition a document from draft to final status.

    Returns the updated document dict, or None if the document was not found.
    """
    table = _get_table()
    pk = f'DOCUMENT#{tenant_id}'
    sk = _sk(package_id, doc_type, version)

    try:
        response = table.update_item(
            Key={'PK': pk, 'SK': sk},
            UpdateExpression='SET #s = :final',
            ConditionExpression='attribute_exists(PK)',
            ExpressionAttributeNames={'#s': 'status'},
            ExpressionAttributeValues={':final': 'final'},
            ReturnValues='ALL_NEW',
        )
        attrs = response.get('Attributes', {})
        return _item_to_dict(attrs) if attrs else None
    except ClientError as e:
        if e.response['Error']['Code'] == 'ConditionalCheckFailedException':
            logger.warning(
                'document_store.finalize_document: item not found [%s/%s/%s v%s]',
                tenant_id, package_id, doc_type, version,
            )
            return None
        logger.error('document_store.finalize_document failed: %s', e)
        return None
    except BotoCoreError as e:
        logger.error('document_store.finalize_document failed: %s', e)
        return None


def list_package_documents(tenant_id: str, package_id: str) -> list[dict]:
    """Return the latest version of each doc_type for a given package.

    Queries all DOCUMENT# items whose SK begins with DOCUMENT#{package_id}#,
    then selects the highest version per doc_type.
    """
    table = _get_table()
    sk_prefix = f'DOCUMENT#{package_id}#'

    try:
        response = table.query(
            KeyConditionExpression=(
                Key('PK').eq(f'DOCUMENT#{tenant_id}')
                & Key('SK').begins_with(sk_prefix)
            ),
        )
        items = [_item_to_dict(i) for i in response.get('Items', [])]
    except (ClientError, BotoCoreError) as e:
        logger.error('document_store.list_package_documents failed: %s', e)
        return []

    latest: dict[str, dict] = {}
    for item in items:
        dt = item.get('doc_type', '')
        if dt not in latest or item['version'] > latest[dt]['version']:
            latest[dt] = item

    return sorted(latest.values(), key=lambda d: d.get('doc_type', ''))


def get_document_history(
    tenant_id: str,
    package_id: str,
    doc_type: str,
) -> list[dict]:
    """Return all versions of a given doc_type within a package, sorted ascending."""
    table = _get_table()
    sk_prefix = f'DOCUMENT#{package_id}#{doc_type}#'

    try:
        response = table.query(
            KeyConditionExpression=(
                Key('PK').eq(f'DOCUMENT#{tenant_id}')
                & Key('SK').begins_with(sk_prefix)
            ),
        )
        items = [_item_to_dict(i) for i in response.get('Items', [])]
        return sorted(items, key=lambda d: d.get('version', 0))
    except (ClientError, BotoCoreError) as e:
        logger.error('document_store.get_document_history failed: %s', e)
        return []

