"""
Document Export Service
Generates DOCX and PDF files from markdown content with NCI/EAGLE branding.
"""
import io
import re
import logging
from datetime import datetime
from typing import Optional, Dict, Any, List

logger = logging.getLogger("eagle.export")

# ── Brand constants ──────────────────────────────────────────────────
NCI_BLUE = "#003366"
NCI_BLUE_RGB = (0, 51, 102)
NCI_BLUE_LIGHT_RGB = (230, 238, 245)   # Light blue for table alt-rows
TABLE_HEADER_TEXT_RGB = (255, 255, 255) # White text on blue header
WATERMARK_TEXT = "DRAFT"
FOOTER_TEXT = "Generated by EAGLE — NCI Acquisition Assistant"


# ══════════════════════════════════════════════════════════════════════
#  DOCX Export
# ══════════════════════════════════════════════════════════════════════

def markdown_to_docx(content: str, title: str = "Document") -> bytes:
    """Convert markdown content to a branded DOCX file. Returns bytes."""
    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor, Cm
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.enum.table import WD_TABLE_ALIGNMENT
        from docx.oxml.ns import qn
    except ImportError:
        logger.warning("python-docx not installed, using fallback")
        return _docx_fallback(content, title)

    doc = Document()

    # ── Document properties ──────────────────────────────────────────
    doc.core_properties.title = title
    doc.core_properties.author = "EAGLE - NCI Acquisition Assistant"
    doc.core_properties.created = datetime.utcnow()

    # ── Page margins ─────────────────────────────────────────────────
    for section in doc.sections:
        section.top_margin = Cm(2.54)
        section.bottom_margin = Cm(2.54)
        section.left_margin = Cm(2.54)
        section.right_margin = Cm(2.54)

    # ── Custom heading styles (NCI blue) ─────────────────────────────
    _setup_docx_styles(doc)

    # ── Header / Footer ──────────────────────────────────────────────
    _add_docx_header_footer(doc, title)

    # ── DRAFT watermark ──────────────────────────────────────────────
    _add_docx_watermark(doc)

    # ── Title block ──────────────────────────────────────────────────
    _add_docx_title_block(doc, title)

    # ── Parse markdown body ──────────────────────────────────────────
    lines = content.split('\n')
    in_table = False
    table_data: List[List[str]] = []
    in_code_block = False
    code_lines: List[str] = []

    for line in lines:
        stripped = line.strip()

        # Code blocks
        if stripped.startswith('```'):
            if in_code_block:
                if code_lines:
                    p = doc.add_paragraph()
                    p.style = 'No Spacing'
                    run = p.add_run('\n'.join(code_lines))
                    run.font.name = 'Courier New'
                    run.font.size = Pt(9)
                    run.font.color.rgb = RGBColor(50, 50, 50)
                code_lines = []
                in_code_block = False
            else:
                in_code_block = True
            continue

        if in_code_block:
            code_lines.append(line)
            continue

        # Tables
        if stripped.startswith('|') and stripped.endswith('|'):
            if '---' in stripped:
                continue
            cells = [c.strip() for c in stripped.split('|')[1:-1]]
            if not in_table:
                in_table = True
                table_data = [cells]
            else:
                table_data.append(cells)
            continue
        elif in_table:
            _add_table_to_doc(doc, table_data)
            table_data = []
            in_table = False

        # Headers
        if stripped.startswith('# '):
            doc.add_heading(stripped[2:], level=1)
        elif stripped.startswith('## '):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith('### '):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith('#### '):
            doc.add_heading(stripped[5:], level=4)
        # Horizontal rules
        elif stripped in ('---', '***', '___'):
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(6)
            p.paragraph_format.space_after = Pt(6)
            run = p.add_run('─' * 60)
            run.font.color.rgb = RGBColor(180, 180, 180)
            run.font.size = Pt(8)
        # Checkboxes (MUST come before bullet check — '- [ ] ' starts with '- ')
        elif stripped.startswith('- [ ] '):
            p = doc.add_paragraph('☐  ' + stripped[6:], style='List Bullet')
        elif stripped.startswith('- [x] ') or stripped.startswith('- [X] '):
            p = doc.add_paragraph('☑  ' + stripped[6:], style='List Bullet')
        # Bullet points
        elif stripped.startswith('- ') or stripped.startswith('* '):
            doc.add_paragraph(stripped[2:], style='List Bullet')
        # Numbered lists
        elif re.match(r'^\d+\.\s', stripped):
            text = re.sub(r'^\d+\.\s', '', stripped)
            doc.add_paragraph(text, style='List Number')
        # Blockquotes
        elif stripped.startswith('> '):
            p = doc.add_paragraph(stripped[2:])
            p.style = 'Quote'
        # Empty lines
        elif not stripped:
            doc.add_paragraph()
        # Regular paragraphs
        else:
            p = doc.add_paragraph()
            _add_formatted_text(p, stripped)

    # Remaining table
    if in_table and table_data:
        _add_table_to_doc(doc, table_data)

    # Save
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.read()


def _setup_docx_styles(doc):
    """Apply NCI blue to heading styles."""
    from docx.shared import Pt, RGBColor

    blue = RGBColor(*NCI_BLUE_RGB)
    heading_sizes = {0: 20, 1: 16, 2: 14, 3: 12}  # Heading 1-4

    for level, size in heading_sizes.items():
        style = doc.styles[f'Heading {level + 1}']
        style.font.color.rgb = blue
        style.font.size = Pt(size)
        style.font.bold = True


def _add_docx_header_footer(doc, title: str):
    """Add branded header and footer with page numbers."""
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    section = doc.sections[0]

    # ── Header ───────────────────────────────────────────────────────
    header = section.header
    header.is_linked_to_previous = False
    hp = header.paragraphs[0]
    hp.alignment = WD_ALIGN_PARAGRAPH.LEFT

    run_eagle = hp.add_run("EAGLE")
    run_eagle.font.size = Pt(9)
    run_eagle.font.bold = True
    run_eagle.font.color.rgb = RGBColor(*NCI_BLUE_RGB)

    run_sep = hp.add_run("  |  ")
    run_sep.font.size = Pt(8)
    run_sep.font.color.rgb = RGBColor(150, 150, 150)

    run_title = hp.add_run(title[:60])
    run_title.font.size = Pt(8)
    run_title.font.color.rgb = RGBColor(100, 100, 100)

    # Thin line under header
    pPr = hp._element.get_or_add_pPr()
    pBdr = OxmlElement('w:pBdr')
    bottom = OxmlElement('w:bottom')
    bottom.set(qn('w:val'), 'single')
    bottom.set(qn('w:sz'), '4')
    bottom.set(qn('w:space'), '4')
    bottom.set(qn('w:color'), '003366')
    pBdr.append(bottom)
    pPr.append(pBdr)

    # ── Footer ───────────────────────────────────────────────────────
    footer = section.footer
    footer.is_linked_to_previous = False
    fp = footer.paragraphs[0]
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run_footer = fp.add_run(FOOTER_TEXT + "  |  Page ")
    run_footer.font.size = Pt(8)
    run_footer.font.color.rgb = RGBColor(120, 120, 120)

    # Page number field
    fldChar1 = OxmlElement('w:fldChar')
    fldChar1.set(qn('w:fldCharType'), 'begin')
    fp.add_run()._element.append(fldChar1)

    instrText = OxmlElement('w:instrText')
    instrText.text = ' PAGE '
    fp.add_run()._element.append(instrText)

    fldChar2 = OxmlElement('w:fldChar')
    fldChar2.set(qn('w:fldCharType'), 'end')
    fp.add_run()._element.append(fldChar2)


def _add_docx_watermark(doc):
    """Add a diagonal DRAFT watermark to the document."""
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    section = doc.sections[0]
    header = section.header

    # WordprocessingML shape for diagonal watermark
    watermark_xml = (
        '<w:r xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"'
        '     xmlns:v="urn:schemas-microsoft-com:vml"'
        '     xmlns:o="urn:schemas-microsoft-com:office:office">'
        '  <w:pict>'
        '    <v:shapetype id="_x0000_t136" coordsize="21600,21600"'
        '      o:spt="136" adj="10800"'
        '      path="m@7,l@8,m@5,21600l@6,21600e">'
        '      <v:formulas>'
        '        <v:f eqn="sum #0 0 10800"/>'
        '        <v:f eqn="prod #0 2 1"/>'
        '        <v:f eqn="sum 21600 0 @1"/>'
        '        <v:f eqn="sum 0 0 @2"/>'
        '        <v:f eqn="sum 21600 0 @3"/>'
        '        <v:f eqn="if @0 @3 0"/>'
        '        <v:f eqn="if @0 21600 @1"/>'
        '        <v:f eqn="if @0 0 @2"/>'
        '        <v:f eqn="if @0 @4 21600"/>'
        '        <v:f eqn="mid @5 @6"/>'
        '        <v:f eqn="mid @8 @5"/>'
        '        <v:f eqn="mid @7 @8"/>'
        '        <v:f eqn="mid @6 @7"/>'
        '        <v:f eqn="sum @6 0 @5"/>'
        '      </v:formulas>'
        '      <v:path textpathok="t" o:connecttype="custom"'
        '        o:connectlocs="@9,0;@10,10800;@11,21600;@12,10800"/>'
        '      <v:textpath on="t" fitshape="t"/>'
        '    </v:shapetype>'
        '    <v:shape id="PowerPlusWaterMarkObject"'
        '      o:spid="_x0000_s2049" type="#_x0000_t136"'
        '      style="position:absolute;margin-left:0;margin-top:0;'
        '             width:500pt;height:100pt;rotation:315;z-index:-251657216;'
        '             mso-position-horizontal:center;mso-position-vertical:center;'
        '             mso-position-horizontal-relative:margin;'
        '             mso-position-vertical-relative:margin"'
        '      o:allowincell="f"'
        '      fillcolor="#E0E0E0" stroked="f">'
        '      <v:fill opacity=".25"/>'
        f'      <v:textpath style="font-family:&quot;Calibri&quot;;font-size:1pt"'
        f'        string="{WATERMARK_TEXT}"/>'
        '    </v:shape>'
        '  </w:pict>'
        '</w:r>'
    )

    try:
        from lxml import etree
        watermark_element = etree.fromstring(watermark_xml)
        # Add to header paragraph
        p = header.paragraphs[0]._element
        p.append(watermark_element)
    except Exception:
        # Watermark is cosmetic — don't fail the export
        logger.debug("Could not add DOCX watermark (lxml may not be available)")


def _add_docx_title_block(doc, title: str):
    """Add a branded title block at the top of the document."""
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    # Title
    p_title = doc.add_paragraph()
    p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p_title.add_run(title)
    run.font.size = Pt(22)
    run.font.bold = True
    run.font.color.rgb = RGBColor(*NCI_BLUE_RGB)

    # Subtitle
    p_sub = doc.add_paragraph()
    p_sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run_sub = p_sub.add_run("National Cancer Institute (NCI)")
    run_sub.font.size = Pt(12)
    run_sub.font.color.rgb = RGBColor(80, 80, 80)

    # Date
    p_date = doc.add_paragraph()
    p_date.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run_date = p_date.add_run(f"Document Date: {datetime.utcnow().strftime('%B %d, %Y')}")
    run_date.font.size = Pt(10)
    run_date.font.color.rgb = RGBColor(120, 120, 120)
    run_date.font.italic = True

    # Status badge
    p_status = doc.add_paragraph()
    p_status.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run_status = p_status.add_run("DRAFT — FOR REVIEW ONLY")
    run_status.font.size = Pt(10)
    run_status.font.bold = True
    run_status.font.color.rgb = RGBColor(180, 80, 0)

    # Spacer
    doc.add_paragraph()


def _add_table_to_doc(doc, table_data: list):
    """Add a branded table to the DOCX document."""
    from docx.shared import Pt, RGBColor
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    if not table_data:
        return

    rows = len(table_data)
    cols = len(table_data[0]) if table_data else 0
    if rows == 0 or cols == 0:
        return

    table = doc.add_table(rows=rows, cols=cols)
    table.style = 'Table Grid'

    for i, row_data in enumerate(table_data):
        row = table.rows[i]
        for j, cell_text in enumerate(row_data):
            if j < len(row.cells):
                cell = row.cells[j]
                cell.text = cell_text

                # Style header row — NCI blue background, white bold text
                if i == 0:
                    shading = OxmlElement('w:shd')
                    shading.set(qn('w:val'), 'clear')
                    shading.set(qn('w:color'), 'auto')
                    shading.set(qn('w:fill'), '003366')
                    cell._element.get_or_add_tcPr().append(shading)

                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.bold = True
                            run.font.color.rgb = RGBColor(*TABLE_HEADER_TEXT_RGB)
                            run.font.size = Pt(10)
                else:
                    # Alternate row shading
                    if i % 2 == 0:
                        shading = OxmlElement('w:shd')
                        shading.set(qn('w:val'), 'clear')
                        shading.set(qn('w:color'), 'auto')
                        shading.set(qn('w:fill'), 'E6EEF5')
                        cell._element.get_or_add_tcPr().append(shading)

                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.font.size = Pt(9)


def _add_formatted_text(paragraph, text: str):
    """Add text with inline formatting (bold, italic, code) to a paragraph."""
    from docx.shared import Pt, RGBColor

    pattern = r'(\*\*.*?\*\*|\*.*?\*|`.*?`)'
    parts = re.split(pattern, text)

    for part in parts:
        if not part:
            continue
        if part.startswith('**') and part.endswith('**'):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        elif part.startswith('*') and part.endswith('*'):
            run = paragraph.add_run(part[1:-1])
            run.italic = True
        elif part.startswith('`') and part.endswith('`'):
            run = paragraph.add_run(part[1:-1])
            run.font.name = 'Courier New'
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(80, 80, 80)
        else:
            paragraph.add_run(part)


def _docx_fallback(content: str, title: str) -> bytes:
    """Fallback when python-docx is not available."""
    header = f"EAGLE Document Export\nTitle: {title}\nGenerated: {datetime.utcnow().isoformat()}\n\n{'=' * 60}\n\n"
    return (header + content).encode('utf-8')


# ══════════════════════════════════════════════════════════════════════
#  PDF Export
# ══════════════════════════════════════════════════════════════════════

def markdown_to_pdf(content: str, title: str = "Document") -> bytes:
    """Convert markdown content to a branded PDF file. Returns bytes."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            PageBreak,
        )
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
    except ImportError:
        logger.warning("reportlab not installed, using fallback")
        return _pdf_fallback(content, title)

    buffer = io.BytesIO()

    nci_blue = colors.Color(
        NCI_BLUE_RGB[0] / 255,
        NCI_BLUE_RGB[1] / 255,
        NCI_BLUE_RGB[2] / 255,
    )
    nci_light = colors.Color(
        NCI_BLUE_LIGHT_RGB[0] / 255,
        NCI_BLUE_LIGHT_RGB[1] / 255,
        NCI_BLUE_LIGHT_RGB[2] / 255,
    )

    # Page template callback for header/footer
    doc_title = title  # capture for closure

    def _on_page(canvas, doc):
        canvas.saveState()
        width, height = letter

        # ── Header line ──────────────────────────────────────────────
        canvas.setStrokeColor(nci_blue)
        canvas.setLineWidth(1.5)
        canvas.line(inch, height - 0.6 * inch, width - inch, height - 0.6 * inch)

        canvas.setFont('Helvetica-Bold', 8)
        canvas.setFillColor(nci_blue)
        canvas.drawString(inch, height - 0.52 * inch, "EAGLE")

        canvas.setFont('Helvetica', 7)
        canvas.setFillColor(colors.grey)
        canvas.drawString(inch + 42, height - 0.52 * inch, f"|  {doc_title[:55]}")

        # Date on right
        canvas.drawRightString(
            width - inch, height - 0.52 * inch,
            datetime.utcnow().strftime('%B %d, %Y'),
        )

        # ── Footer ───────────────────────────────────────────────────
        canvas.setStrokeColor(colors.Color(0.8, 0.8, 0.8))
        canvas.setLineWidth(0.5)
        canvas.line(inch, 0.65 * inch, width - inch, 0.65 * inch)

        canvas.setFont('Helvetica', 7)
        canvas.setFillColor(colors.grey)
        canvas.drawString(inch, 0.5 * inch, FOOTER_TEXT)
        canvas.drawRightString(width - inch, 0.5 * inch, f"Page {doc.page}")

        # ── DRAFT watermark ──────────────────────────────────────────
        canvas.setFont('Helvetica-Bold', 60)
        canvas.setFillColor(colors.Color(0.9, 0.9, 0.9))
        canvas.saveState()
        canvas.translate(width / 2, height / 2)
        canvas.rotate(45)
        canvas.drawCentredString(0, 0, WATERMARK_TEXT)
        canvas.restoreState()

        canvas.restoreState()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=0.9 * inch,
        bottomMargin=0.9 * inch,
    )

    styles = getSampleStyleSheet()

    # ── Custom styles ────────────────────────────────────────────────
    styles.add(ParagraphStyle(
        name='EagleTitle',
        parent=styles['Title'],
        fontSize=22,
        textColor=nci_blue,
        spaceAfter=6,
        alignment=TA_CENTER,
    ))
    styles.add(ParagraphStyle(
        name='EagleSubtitle',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.grey,
        alignment=TA_CENTER,
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name='EagleStatus',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.Color(0.7, 0.3, 0),
        alignment=TA_CENTER,
        spaceBefore=4,
        spaceAfter=20,
    ))
    styles.add(ParagraphStyle(
        name='EagleH1',
        parent=styles['Heading1'],
        fontSize=16,
        textColor=nci_blue,
        spaceAfter=12,
        spaceBefore=20,
        fontName='Helvetica-Bold',
    ))
    styles.add(ParagraphStyle(
        name='EagleH2',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=nci_blue,
        spaceAfter=10,
        spaceBefore=16,
        fontName='Helvetica-Bold',
    ))
    styles.add(ParagraphStyle(
        name='EagleH3',
        parent=styles['Heading3'],
        fontSize=12,
        textColor=nci_blue,
        spaceAfter=8,
        spaceBefore=12,
        fontName='Helvetica-Bold',
    ))
    styles.add(ParagraphStyle(
        name='EagleH4',
        parent=styles['Heading4'],
        fontSize=11,
        textColor=nci_blue,
        spaceAfter=6,
        spaceBefore=10,
        fontName='Helvetica-BoldOblique',
    ))
    styles.add(ParagraphStyle(
        name='EagleCode',
        parent=styles['Code'],
        fontSize=8,
        fontName='Courier',
        backColor=colors.Color(0.95, 0.95, 0.95),
        borderColor=colors.Color(0.85, 0.85, 0.85),
        borderWidth=0.5,
        borderPadding=4,
    ))
    styles.add(ParagraphStyle(
        name='EagleBullet',
        parent=styles['Normal'],
        leftIndent=24,
        bulletIndent=12,
        spaceBefore=2,
        spaceAfter=2,
    ))
    styles.add(ParagraphStyle(
        name='EagleBlockquote',
        parent=styles['Normal'],
        leftIndent=24,
        textColor=colors.Color(0.35, 0.35, 0.35),
        fontName='Helvetica-Oblique',
        fontSize=10,
        borderColor=nci_blue,
        borderWidth=2,
        borderPadding=(8, 4, 4, 12),
        spaceBefore=6,
        spaceAfter=6,
    ))

    story = []

    # ── Title block ──────────────────────────────────────────────────
    story.append(Paragraph(_escape_html(title), styles['EagleTitle']))
    story.append(Paragraph("National Cancer Institute (NCI)", styles['EagleSubtitle']))
    story.append(Paragraph(
        f"Document Date: {datetime.utcnow().strftime('%B %d, %Y')}",
        styles['EagleSubtitle'],
    ))
    story.append(Paragraph("<b>DRAFT — FOR REVIEW ONLY</b>", styles['EagleStatus']))
    story.append(Spacer(1, 12))

    # ── Parse markdown ───────────────────────────────────────────────
    lines = content.split('\n')
    in_code_block = False
    code_lines: List[str] = []
    in_table = False
    table_data: List[List[str]] = []
    for line in lines:
        stripped = line.strip()

        # Code blocks
        if stripped.startswith('```'):
            if in_code_block:
                if code_lines:
                    code_text = '<br/>'.join(_escape_html(cl) for cl in code_lines)
                    story.append(Paragraph(code_text, styles['EagleCode']))
                    story.append(Spacer(1, 6))
                code_lines = []
                in_code_block = False
            else:
                in_code_block = True
            continue

        if in_code_block:
            code_lines.append(line)
            continue

        # Tables
        if stripped.startswith('|') and stripped.endswith('|'):
            if '---' in stripped:
                continue
            cells = [c.strip() for c in stripped.split('|')[1:-1]]
            if not in_table:
                in_table = True
                table_data = [cells]
            else:
                table_data.append(cells)
            continue
        elif in_table:
            _add_table_to_pdf(story, table_data, styles, nci_blue, nci_light)
            table_data = []
            in_table = False

        # Headers
        if stripped.startswith('# '):
            story.append(Paragraph(_escape_html(stripped[2:]), styles['EagleH1']))
        elif stripped.startswith('## '):
            story.append(Paragraph(_escape_html(stripped[3:]), styles['EagleH2']))
        elif stripped.startswith('### '):
            story.append(Paragraph(_escape_html(stripped[4:]), styles['EagleH3']))
        elif stripped.startswith('#### '):
            story.append(Paragraph(_escape_html(stripped[5:]), styles['EagleH4']))
        # Horizontal rules
        elif stripped in ('---', '***', '___'):
            from reportlab.platypus import HRFlowable
            story.append(HRFlowable(
                width="100%", thickness=1,
                color=colors.Color(0.8, 0.8, 0.8),
                spaceBefore=8, spaceAfter=8,
            ))
        # Checkboxes (before bullets — '- [ ] ' starts with '- ')
        elif stripped.startswith('- [ ] '):
            story.append(Paragraph(
                f"☐  {_markdown_to_reportlab(stripped[6:])}",
                styles['EagleBullet'],
            ))
        elif stripped.startswith('- [x] ') or stripped.startswith('- [X] '):
            story.append(Paragraph(
                f"☑  {_markdown_to_reportlab(stripped[6:])}",
                styles['EagleBullet'],
            ))
        # Bullet points
        elif stripped.startswith('- ') or stripped.startswith('* '):
            story.append(Paragraph(
                f"•  {_markdown_to_reportlab(stripped[2:])}",
                styles['EagleBullet'],
            ))
        # Numbered lists (preserve the number)
        elif re.match(r'^(\d+)\.\s', stripped):
            m = re.match(r'^(\d+)\.\s(.*)', stripped)
            num = m.group(1)
            text = m.group(2)
            story.append(Paragraph(
                f"{num}.  {_markdown_to_reportlab(text)}",
                styles['EagleBullet'],
            ))
        # Blockquotes
        elif stripped.startswith('> '):
            story.append(Paragraph(
                _markdown_to_reportlab(stripped[2:]),
                styles['EagleBlockquote'],
            ))
        # Empty lines
        elif not stripped:
            story.append(Spacer(1, 6))
        # Regular paragraphs
        else:
            text = _markdown_to_reportlab(stripped)
            story.append(Paragraph(text, styles['Normal']))

    # Remaining table
    if in_table and table_data:
        _add_table_to_pdf(story, table_data, styles, nci_blue, nci_light)

    # Build
    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)
    buffer.seek(0)
    return buffer.read()


def _add_table_to_pdf(story, table_data: list, styles, nci_blue, nci_light):
    """Add a branded table to the PDF story."""
    from reportlab.platypus import Table, TableStyle, Paragraph, Spacer
    from reportlab.lib import colors

    if not table_data:
        return

    wrapped_data = []
    for row in table_data:
        wrapped_row = [Paragraph(_escape_html(cell), styles['Normal']) for cell in row]
        wrapped_data.append(wrapped_row)

    table = Table(wrapped_data, repeatRows=1)

    style_cmds = [
        # Header row — NCI blue background, white bold text
        ('BACKGROUND', (0, 0), (-1, 0), nci_blue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 0), (-1, 0), 6),
        # Body rows
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('TOPPADDING', (0, 1), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 4),
        # Grid
        ('GRID', (0, 0), (-1, -1), 0.5, colors.Color(0.75, 0.75, 0.75)),
        ('LINEBELOW', (0, 0), (-1, 0), 1.5, nci_blue),
    ]

    # Alternate row shading
    for i in range(1, len(table_data)):
        if i % 2 == 0:
            style_cmds.append(('BACKGROUND', (0, i), (-1, i), nci_light))

    table.setStyle(TableStyle(style_cmds))
    story.append(table)
    story.append(Spacer(1, 12))


def _escape_html(text: str) -> str:
    """Escape HTML special characters for reportlab Paragraph markup."""
    return (text
            .replace('&', '&amp;')
            .replace('<', '&lt;')
            .replace('>', '&gt;'))


def _markdown_to_reportlab(text: str) -> str:
    """Convert markdown inline formatting to reportlab XML tags."""
    text = _escape_html(text)
    # Bold
    text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
    # Italic
    text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)
    # Code
    text = re.sub(r'`(.+?)`', r'<font name="Courier" color="#505050">\1</font>', text)
    return text


def _pdf_fallback(content: str, title: str) -> bytes:
    """Fallback when reportlab is not available."""
    header = f"EAGLE Document Export (PDF fallback - text format)\nTitle: {title}\nGenerated: {datetime.utcnow().isoformat()}\n\n{'=' * 60}\n\n"
    return (header + content).encode('utf-8')


# ══════════════════════════════════════════════════════════════════════
#  Export Orchestrator
# ══════════════════════════════════════════════════════════════════════

def export_document(
    content: str,
    format: str,
    title: str = "Document",
    metadata: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Export document to specified format.

    Args:
        content: Markdown content
        format: "docx", "pdf", or "md"
        title: Document title
        metadata: Optional metadata to include

    Returns:
        Dict with: data (bytes), filename, content_type, size
    """
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    safe_title = re.sub(r'[^\w\-]', '_', title)[:50]

    if format.lower() == "docx":
        data = markdown_to_docx(content, title)
        filename = f"{safe_title}_{timestamp}.docx"
        content_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    elif format.lower() == "pdf":
        data = markdown_to_pdf(content, title)
        filename = f"{safe_title}_{timestamp}.pdf"
        content_type = "application/pdf"
    elif format.lower() in ("md", "markdown"):
        data = content.encode('utf-8')
        filename = f"{safe_title}_{timestamp}.md"
        content_type = "text/markdown"
    else:
        raise ValueError(f"Unsupported format: {format}. Use docx, pdf, or md.")

    return {
        "data": data,
        "filename": filename,
        "content_type": content_type,
        "size_bytes": len(data),
        "format": format.lower(),
        "generated_at": datetime.utcnow().isoformat(),
    }
