"""
Tests for document_agent.py — Agent-as-Tool document generator.

Covers:
  - Template loading (all 10 doc types)
  - Required fields YAML loading and validation
  - Prompt construction
  - Appendix parsing (Appendix A omissions, Appendix B rationale)
  - Required field validation
  - Title extraction
  - Full generate_document flow with mocked model
  - ReasoningStore section/justification entries

Run: pytest server/tests/test_document_agent.py -v
"""

import json
import os
import sys
from unittest.mock import MagicMock, patch, PropertyMock

import pytest

# Ensure server/ is on sys.path
_server_dir = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
if _server_dir not in sys.path:
    sys.path.insert(0, _server_dir)


# ── Constants ────────────────────────────────────────────────────────

ALL_DOC_TYPES = [
    "sow", "igce", "market_research", "justification",
    "acquisition_plan", "eval_criteria", "security_checklist",
    "section_508", "cor_certification", "contract_type_justification",
]

TEMPLATE_DOC_TYPES = ["sow", "igce", "acquisition_plan", "justification", "market_research"]
NO_TEMPLATE_DOC_TYPES = [
    "eval_criteria", "security_checklist", "section_508",
    "cor_certification", "contract_type_justification",
]

MOCK_SOW_OUTPUT = """# STATEMENT OF WORK (SOW)
## Cloud Migration Services
### National Cancer Institute (NCI)

**Document Status:** DRAFT — Generated 2026-03-11

---

## 1. BACKGROUND AND PURPOSE

The National Cancer Institute requires cloud migration services to transition
legacy on-premises infrastructure to AWS GovCloud.

## 2. SCOPE

The contractor shall provide all personnel and services necessary to complete
the migration of 15 application workloads.

## 3. PERIOD OF PERFORMANCE

Base period: 12 months from date of award.
Option Period 1: 12 months.

## 4. APPLICABLE DOCUMENTS AND STANDARDS

- Federal Acquisition Regulation (FAR)
- NIST SP 800-53 Rev 5
- FedRAMP Moderate baseline

## 5. TASKS AND REQUIREMENTS

### Task 1: Assessment and Planning
Conduct comprehensive assessment of existing infrastructure.

### Task 2: Migration Execution
Execute phased migration using AWS Migration Hub.

## 6. DELIVERABLES

| ID | Deliverable | Due Date | Format |
|----|-------------|----------|--------|
| D-1 | Migration Assessment Report | 30 days | PDF |
| D-2 | Monthly Status Reports | Monthly | PDF |

## 7. GOVERNMENT-FURNISHED PROPERTY (GFP)

AWS GovCloud account access will be provided by the Government.

## 8. QUALITY ASSURANCE SURVEILLANCE PLAN (QASP)

| Standard | AQL | Method |
|----------|-----|--------|
| Migration uptime | 99.9% | Monitoring |

## 9. PLACE OF PERFORMANCE

National Cancer Institute, Bethesda, MD 20892.

## 10. SECURITY REQUIREMENTS

All contractor personnel must obtain NIH Public Trust clearance.
FedRAMP Moderate authorization required for all cloud services.

---

## Appendix A: Omissions & Information Gaps

| Section | Status | Reason | Information Needed |
|---------|--------|--------|-------------------|
| 7. GFP | Partial | Only AWS accounts mentioned | Full list of government-furnished items |
| Travel | Omitted | No travel discussed | Travel requirements if any |
| Contractor Personnel | Default | Used standard NCI requirements | Specific labor categories and qualifications |

## Appendix B: AI Decision Rationale

**Contract Type Selection: Firm-Fixed-Price (FFP)**
The estimated scope is well-defined with clear deliverables and measurable outcomes.
FFP is appropriate per FAR 16.202 for well-defined requirements.

**Security Level: Moderate**
Cloud migration involving government data requires FedRAMP Moderate baseline
per NIST SP 800-53 Rev 5 and NIH security policies.

---
*This document was generated by EAGLE — NCI Acquisition Assistant*
"""

MOCK_CONVERSATION = """[USER]: I need to migrate our legacy systems to AWS cloud. We have about 15 applications running on-premises.

[ASSISTANT]: I can help with that. What's your timeline and budget?

[USER]: 12 months, budget is around $2M. We need FedRAMP compliance.

[ASSISTANT]: I'll prepare a Statement of Work for the cloud migration.
"""


# ══════════════════════════════════════════════════════════════════════
# T1 — Template Loading
# ══════════════════════════════════════════════════════════════════════

class TestTemplateLoading:
    """Verify templates load correctly for all doc types."""

    @pytest.mark.parametrize("doc_type", TEMPLATE_DOC_TYPES)
    def test_template_loads_for_supported_types(self, doc_type):
        from app.document_agent import _load_template
        content = _load_template(doc_type)
        assert len(content) > 100, f"Template for {doc_type} too short: {len(content)} chars"
        assert "{{" in content, f"Template for {doc_type} should have placeholder tokens"

    @pytest.mark.parametrize("doc_type", NO_TEMPLATE_DOC_TYPES)
    def test_fallback_message_for_no_template_types(self, doc_type):
        from app.document_agent import _load_template
        content = _load_template(doc_type)
        assert "No dedicated template" in content or "standard" in content.lower()

    def test_unknown_type_returns_fallback(self):
        from app.document_agent import _load_template
        content = _load_template("nonexistent_type")
        assert "No dedicated template" in content or "standard" in content.lower()


# ══════════════════════════════════════════════════════════════════════
# T2 — Required Fields YAML
# ══════════════════════════════════════════════════════════════════════

class TestRequiredFields:
    """Verify required_fields.yaml loads and has correct structure."""

    def test_yaml_loads_all_doc_types(self):
        from app.document_agent import _load_required_fields, _required_fields_cache
        # Reset cache
        import app.document_agent as mod
        mod._required_fields_cache = None

        for doc_type in ALL_DOC_TYPES:
            fields = _load_required_fields(doc_type)
            assert isinstance(fields, dict), f"No entry for {doc_type}"
            assert "display_name" in fields, f"Missing display_name for {doc_type}"
            assert "required_sections" in fields, f"Missing required_sections for {doc_type}"

    def test_sow_has_expected_required_sections(self):
        import app.document_agent as mod
        mod._required_fields_cache = None
        fields = mod._load_required_fields("sow")
        required = fields["required_sections"]
        assert "title" in required
        assert "scope" in required
        assert "tasks" in required
        assert "deliverables" in required

    def test_unknown_type_returns_empty_dict(self):
        from app.document_agent import _load_required_fields
        result = _load_required_fields("totally_fake")
        assert result == {}


# ══════════════════════════════════════════════════════════════════════
# T3 — Prompt Construction
# ══════════════════════════════════════════════════════════════════════

class TestPromptConstruction:
    """Verify prompt building produces well-structured output."""

    def test_prompt_contains_template(self):
        from app.document_agent import _build_prompt
        prompt = _build_prompt(
            doc_type="sow",
            template_content="## 1. BACKGROUND\n{{DESCRIPTION}}",
            conversation_context="User wants cloud migration",
            state_snapshot="(no state)",
            required_fields={"display_name": "Statement of Work", "required_sections": ["title", "scope"]},
        )
        assert "<template>" in prompt
        assert "{{DESCRIPTION}}" in prompt
        assert "<context>" in prompt
        assert "Statement of Work" in prompt

    def test_prompt_includes_special_instructions(self):
        from app.document_agent import _build_prompt
        prompt = _build_prompt(
            doc_type="sow",
            template_content="template text",
            conversation_context="context",
            state_snapshot="state",
            required_fields={"display_name": "SOW", "required_sections": []},
            special_instructions="Emphasize security requirements and FedRAMP",
        )
        assert "Emphasize security requirements and FedRAMP" in prompt
        assert "Special Instructions" in prompt

    def test_prompt_without_special_instructions_has_no_block(self):
        from app.document_agent import _build_prompt
        prompt = _build_prompt(
            doc_type="sow",
            template_content="template text",
            conversation_context="context",
            state_snapshot="state",
            required_fields={"display_name": "SOW", "required_sections": []},
            special_instructions="",
        )
        assert "Special Instructions" not in prompt

    def test_prompt_lists_required_fields(self):
        from app.document_agent import _build_prompt
        prompt = _build_prompt(
            doc_type="sow",
            template_content="template",
            conversation_context="context",
            state_snapshot="state",
            required_fields={
                "display_name": "SOW",
                "required_sections": ["title", "background_and_purpose", "scope"],
                "recommended_sections": ["qasp"],
            },
        )
        assert "Background And Purpose" in prompt
        assert "Scope" in prompt
        assert "Qasp" in prompt


# ══════════════════════════════════════════════════════════════════════
# T4 — Appendix Parsing
# ══════════════════════════════════════════════════════════════════════

class TestAppendixParsing:
    """Verify appendix A/B are correctly parsed from generated content."""

    def test_parse_both_appendices(self):
        from app.document_agent import _parse_appendices
        main, omissions, reasoning = _parse_appendices(MOCK_SOW_OUTPUT)
        assert "STATEMENT OF WORK" in main
        assert "Appendix A" in omissions
        assert "Appendix B" in reasoning
        assert "GFP" in omissions
        assert "Firm-Fixed-Price" in reasoning

    def test_parse_no_appendices(self):
        from app.document_agent import _parse_appendices
        content = "# Simple Document\n\nJust content, no appendices."
        main, omissions, reasoning = _parse_appendices(content)
        assert main == content
        assert omissions == ""
        assert reasoning == ""

    def test_parse_only_appendix_a(self):
        from app.document_agent import _parse_appendices
        content = "# Doc\n\n## Appendix A: Gaps\n\n| Section | Status | Reason | Needed |\n|---|---|---|---|\n| Security | Omitted | Not discussed | Data classification |"
        main, omissions, reasoning = _parse_appendices(content)
        assert "# Doc" in main
        assert "Security" in omissions
        assert reasoning == ""

    def test_parse_omission_table(self):
        from app.document_agent import _parse_omission_table
        md = """## Appendix A: Omissions
| Section | Status | Reason | Information Needed |
|---------|--------|--------|-------------------|
| 7. GFP | Partial | Only AWS accounts | Full list |
| Travel | Omitted | No travel discussed | Requirements |"""
        entries = _parse_omission_table(md)
        assert len(entries) == 2
        assert entries[0]["section"] == "7. GFP"
        assert entries[0]["status"] == "Partial"
        assert entries[1]["section"] == "Travel"
        assert entries[1]["status"] == "Omitted"

    def test_parse_justification_entries(self):
        from app.document_agent import _parse_justification_entries
        md = """## Appendix B: AI Decision Rationale

**Contract Type: FFP**
Well-defined requirements support FFP per FAR 16.202.

**Security Level: Moderate**
FedRAMP Moderate required for government data.
"""
        entries = _parse_justification_entries(md)
        assert len(entries) == 2
        assert entries[0]["decision"] == "Contract Type: FFP"
        assert "FAR 16.202" in entries[0]["reasoning"]
        assert entries[1]["decision"] == "Security Level: Moderate"


# ══════════════════════════════════════════════════════════════════════
# T5 — Required Field Validation
# ══════════════════════════════════════════════════════════════════════

class TestFieldValidation:
    """Verify required field detection in generated content."""

    def test_sow_with_all_fields_passes(self):
        from app.document_agent import _validate_required_fields
        missing = _validate_required_fields(
            MOCK_SOW_OUTPUT,
            ["title", "background_and_purpose", "scope", "period_of_performance", "tasks", "deliverables"],
        )
        assert missing == [], f"Unexpected missing fields: {missing}"

    def test_missing_fields_detected(self):
        from app.document_agent import _validate_required_fields
        sparse_content = "# Simple SOW\n\nSome background information."
        missing = _validate_required_fields(
            sparse_content,
            ["title", "scope", "tasks", "deliverables", "period_of_performance"],
        )
        # Should detect missing scope, tasks, deliverables, period
        assert len(missing) > 0
        assert "tasks" in missing or "deliverables" in missing

    def test_empty_content_returns_empty(self):
        from app.document_agent import _validate_required_fields
        assert _validate_required_fields("", ["title", "scope"]) == []

    def test_empty_required_returns_empty(self):
        from app.document_agent import _validate_required_fields
        assert _validate_required_fields("any content", []) == []


# ══════════════════════════════════════════════════════════════════════
# T6 — Title Extraction
# ══════════════════════════════════════════════════════════════════════

class TestTitleExtraction:
    """Verify title is extracted from document content."""

    def test_extracts_h1_title(self):
        from app.document_agent import _extract_title
        title = _extract_title("# STATEMENT OF WORK (SOW)\n## Cloud Migration", "sow")
        assert title == "STATEMENT OF WORK (SOW)"

    def test_extracts_h2_when_no_h1(self):
        from app.document_agent import _extract_title
        title = _extract_title("## Cloud Migration\n\nSome content", "sow")
        assert title == "Cloud Migration"

    def test_fallback_title_when_no_heading(self):
        from app.document_agent import _extract_title
        title = _extract_title("No headings at all in this document.", "sow")
        assert "Statement of Work" in title or "Untitled" in title


# ══════════════════════════════════════════════════════════════════════
# T7 — Full generate_document Flow (Mocked Model)
# ══════════════════════════════════════════════════════════════════════

class TestGenerateDocumentFlow:
    """End-to-end test with mocked model call."""

    def _mock_model_result(self):
        """Create a mock that returns MOCK_SOW_OUTPUT when called."""
        mock_agent_cls = MagicMock()
        mock_agent_instance = MagicMock()
        mock_agent_instance.return_value = MOCK_SOW_OUTPUT
        mock_agent_cls.return_value = mock_agent_instance
        return mock_agent_cls

    def test_successful_generation(self):
        from app.document_agent import generate_document

        with patch("app.document_agent._call_model", return_value=MOCK_SOW_OUTPUT), \
             patch("app.document_agent._load_conversation_context", return_value=MOCK_CONVERSATION), \
             patch("app.document_agent._load_state_snapshot", return_value="(no state)"):
            result = generate_document(
                doc_type="sow",
                session_id="tenant#advanced#user#sess-1",
                tenant_id="test-tenant",
                user_id="test-user",
            )

        assert result.success is True
        assert result.doc_type == "sow"
        assert "STATEMENT OF WORK" in result.title
        assert result.word_count > 100
        assert len(result.omissions) > 0  # Appendix A parsed
        assert len(result.justifications) > 0  # Appendix B parsed
        assert result.missing_required == []  # All required fields present

    def test_invalid_doc_type(self):
        from app.document_agent import generate_document
        result = generate_document(
            doc_type="bogus",
            session_id="tenant#advanced#user#sess-1",
            tenant_id="test-tenant",
            user_id="test-user",
        )
        assert result.success is False
        assert "bogus" in result.error

    def test_model_failure_returns_error(self):
        from app.document_agent import generate_document

        with patch("app.document_agent._call_model", side_effect=RuntimeError("Bedrock timeout")), \
             patch("app.document_agent._load_conversation_context", return_value="context"), \
             patch("app.document_agent._load_state_snapshot", return_value="state"):
            result = generate_document(
                doc_type="sow",
                session_id="tenant#advanced#user#sess-1",
                tenant_id="test-tenant",
                user_id="test-user",
            )

        assert result.success is False
        assert "Model call failed" in result.error

    def test_empty_model_response_returns_error(self):
        from app.document_agent import generate_document

        with patch("app.document_agent._call_model", return_value=""), \
             patch("app.document_agent._load_conversation_context", return_value="context"), \
             patch("app.document_agent._load_state_snapshot", return_value="state"):
            result = generate_document(
                doc_type="sow",
                session_id="tenant#advanced#user#sess-1",
                tenant_id="test-tenant",
                user_id="test-user",
            )

        assert result.success is False
        assert "empty" in result.error.lower()

    def test_special_instructions_passed_to_prompt(self):
        from app.document_agent import generate_document

        captured_prompt = {}

        def capture_model_call(prompt, model=None):
            captured_prompt["value"] = prompt
            return MOCK_SOW_OUTPUT

        with patch("app.document_agent._call_model", side_effect=capture_model_call), \
             patch("app.document_agent._load_conversation_context", return_value="context"), \
             patch("app.document_agent._load_state_snapshot", return_value="state"):
            result = generate_document(
                doc_type="sow",
                session_id="tenant#advanced#user#sess-1",
                tenant_id="test-tenant",
                user_id="test-user",
                special_instructions="Focus on cybersecurity and zero trust",
            )

        assert result.success is True
        assert "Focus on cybersecurity and zero trust" in captured_prompt["value"]

    @pytest.mark.parametrize("doc_type", ALL_DOC_TYPES)
    def test_all_doc_types_generate(self, doc_type):
        """Every doc type should at least attempt generation without crashing."""
        from app.document_agent import generate_document

        minimal_output = f"# {doc_type.upper()}\n\nContent for {doc_type}.\n\n---\n*This document was generated by EAGLE*"

        with patch("app.document_agent._call_model", return_value=minimal_output), \
             patch("app.document_agent._load_conversation_context", return_value="context"), \
             patch("app.document_agent._load_state_snapshot", return_value="state"):
            result = generate_document(
                doc_type=doc_type,
                session_id="tenant#advanced#user#sess-1",
                tenant_id="test-tenant",
                user_id="test-user",
            )

        assert result.success is True
        assert result.doc_type == doc_type
        assert result.word_count > 0


# ══════════════════════════════════════════════════════════════════════
# T8 — ReasoningStore Section/Justification Entries
# ══════════════════════════════════════════════════════════════════════

class TestReasoningStoreExtensions:
    """Verify new section and justification entry types."""

    def test_add_section_entry(self):
        from app.stores.reasoning_store import ReasoningLog
        log = ReasoningLog("sess-1", "tenant", "user")
        log.add_section(
            section_name="Security Requirements",
            status="omitted",
            reason="No data classification provided",
            info_needed="ATO status, FISMA level",
        )
        assert len(log.section_entries) == 1
        assert log.section_entries[0].section_name == "Security Requirements"
        assert log.section_entries[0].status == "omitted"

    def test_add_justification_entry(self):
        from app.stores.reasoning_store import ReasoningLog
        log = ReasoningLog("sess-1", "tenant", "user")
        log.add_justification(
            decision="Contract Type: FFP",
            reasoning="Well-defined scope supports firm pricing.",
            far_basis="FAR 16.202",
            confidence="high",
        )
        assert len(log.justification_entries) == 1
        assert log.justification_entries[0].decision == "Contract Type: FFP"
        assert log.justification_entries[0].far_basis == "FAR 16.202"

    def test_omissions_appendix_format(self):
        from app.stores.reasoning_store import ReasoningLog
        log = ReasoningLog("sess-1", "tenant", "user")
        log.add_section("GFP", "partial", "Only AWS", "Full list")
        log.add_section("Travel", "omitted", "Not discussed", "Travel reqs")
        md = log.to_omissions_appendix()
        assert "Appendix A" in md
        assert "GFP" in md
        assert "Travel" in md
        assert "| GFP | Partial | Only AWS | Full list |" in md

    def test_justification_appendix_format(self):
        from app.stores.reasoning_store import ReasoningLog
        log = ReasoningLog("sess-1", "tenant", "user")
        log.add_justification("Set-Aside: Small Business", "Rule of Two satisfied", "FAR 19.502-2(b)")
        md = log.to_justification_appendix()
        assert "Appendix B" in md
        assert "Set-Aside: Small Business" in md
        assert "FAR 19.502-2(b)" in md

    def test_empty_appendices_return_empty(self):
        from app.stores.reasoning_store import ReasoningLog
        log = ReasoningLog("sess-1", "tenant", "user")
        assert log.to_omissions_appendix() == ""
        assert log.to_justification_appendix() == ""

    def test_legacy_appendix_still_works(self):
        from app.stores.reasoning_store import ReasoningLog
        log = ReasoningLog("sess-1", "tenant", "user")
        log.add("tool_call", "create_document", "Generating SOW", "SOW created", confidence="high")
        md = log.to_appendix_markdown()
        assert "Appendix: AI Decision Rationale" in md
        assert "create_document" in md

    def test_full_json_serialization(self):
        from app.stores.reasoning_store import ReasoningLog
        log = ReasoningLog("sess-1", "tenant", "user")
        log.add("tool_call", "search_far", "Checking FAR", "Found clause")
        log.add_section("Security", "partial", "Limited info", "FISMA level")
        log.add_justification("FFP", "Clear scope", "FAR 16.202")
        data = log.to_full_json()
        assert len(data["entries"]) == 1
        assert len(data["sections"]) == 1
        assert len(data["justifications"]) == 1

    def test_save_includes_all_entry_types(self):
        """Verify save() serializes section and justification entries."""
        from app.stores.reasoning_store import ReasoningLog
        log = ReasoningLog("sess-1", "tenant", "user")
        log.add("tool_call", "test", "test", "test")
        log.add_section("GFP", "omitted", "Not discussed", "")
        log.add_justification("FFP", "Clear scope", "FAR 16.202")

        mock_table = MagicMock()
        with patch("app.stores.reasoning_store._get_table", return_value=mock_table):
            log.save()

        mock_table.put_item.assert_called_once()
        item = mock_table.put_item.call_args[1]["Item"]
        assert item["entry_count"] == 1
        assert item["section_count"] == 1
        assert item["justification_count"] == 1
        assert "section_entries" in item
        assert "justification_entries" in item


# ══════════════════════════════════════════════════════════════════════
# T9 — Tool Signature Trace (Strands Integration)
# ══════════════════════════════════════════════════════════════════════

class TestToolSignatureTrace:
    """Verify the generate_document tool schema is correctly registered."""

    def test_generate_document_in_eagle_tools(self):
        """The generate_document tool schema exists in EAGLE_TOOLS."""
        from app.strands_agentic_service import EAGLE_TOOLS
        tool_names = [t["name"] for t in EAGLE_TOOLS]
        assert "generate_document" in tool_names

    def test_generate_document_schema_shape(self):
        """The schema has correct required fields and enum values."""
        from app.strands_agentic_service import EAGLE_TOOLS
        gen_doc = next(t for t in EAGLE_TOOLS if t["name"] == "generate_document")
        schema = gen_doc["input_schema"]
        assert schema["required"] == ["doc_type"]
        props = schema["properties"]
        assert "doc_type" in props
        assert "special_instructions" in props
        assert "sow" in props["doc_type"]["enum"]
        assert len(props["doc_type"]["enum"]) == 10

    def test_create_document_still_exists_as_fallback(self):
        """Legacy create_document tool is still registered."""
        from app.strands_agentic_service import EAGLE_TOOLS
        tool_names = [t["name"] for t in EAGLE_TOOLS]
        assert "create_document" in tool_names

    def test_all_tool_signatures_trace(self):
        """Dump all registered tool names and their required params — trace data."""
        from app.strands_agentic_service import EAGLE_TOOLS
        trace = []
        for tool_def in EAGLE_TOOLS:
            name = tool_def["name"]
            schema = tool_def.get("input_schema", {})
            required = schema.get("required", [])
            props = list(schema.get("properties", {}).keys())
            trace.append({
                "name": name,
                "required": required,
                "params": props,
            })
        # Verify we have a reasonable number of tools
        assert len(trace) >= 10, f"Expected 10+ tools, got {len(trace)}"
        # Print trace for visibility
        print("\n\n=== EAGLE TOOL SIGNATURE TRACE ===")
        for t in trace:
            req_str = ", ".join(t["required"]) if t["required"] else "(none)"
            opt = [p for p in t["params"] if p not in t["required"]]
            opt_str = ", ".join(opt) if opt else "(none)"
            print(f"  {t['name']}")
            print(f"    required: {req_str}")
            print(f"    optional: {opt_str}")
        print(f"\n  Total tools: {len(trace)}")
        print("=== END TRACE ===\n")
